# Generated by Django 2.2.5 on 2019-09-30 14:41

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_server', '0002_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_path',
            field=models.FilePathField(default=django.core.files.storage.FileSystemStorage(location='/media/music'), path=django.core.files.storage.FileSystemStorage(location='/media/music')),
        ),
    ]
